name: dbt_sentinel_run

on:
  push:
    branches: [ main ]
  workflow_dispatch: 

jobs:
  run_dbt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install dbt-bigquery

      - name: Create Key File
        run: |
          # We create the key folder at the SAME level as ltv_sentinel_dbt
          mkdir -p LTV-Sentil/key
          echo "${{ secrets.GCP_SA_KEY }}" > LTV-Sentil/key/service_account.json

      - name: Run dbt
        # This points to the folder that actually contains dbt_project.yml
        working-directory: LTV-Sentil/ltv_sentinel_dbt
        env:
          # We tell dbt to look "up" one level for the key folder we just created
          DBT_GOOGLE_KEYFILE: ../key/service_account.json
        run: |
          dbt run --profiles-dir .
          dbt test --profiles-dir .