name: dbt_sentinel_run

on:
  push:
    branches: [ main ]
  workflow_dispatch: 

jobs:
  run_dbt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install dbt-bigquery

      - name: Create Key File
        run: |
          # Step into the first LTV-Sentil and make the key folder
          mkdir -p LTV-Sentil/key
          echo "${{ secrets.GCP_SA_KEY }}" > LTV-Sentil/key/service_account.json

      - name: Run dbt
        # This is the fix: GitHub already starts inside 'LTV-Sentil' (the repo).
        # We only need to go into the SUB-FOLDER 'ltv_sentinel_dbt'.
        working-directory: LTV-Sentil/ltv_sentinel_dbt
        env:
          DBT_GOOGLE_KEYFILE: ../key/service_account.json
        run: |
          dbt run --profiles-dir .
          dbt test --profiles-dir .