name: dbt_sentinel_run

on:
  push:
    branches: [ main ]
  workflow_dispatch: 

jobs:
  run_dbt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install dbt-bigquery

      - name: Create Key File
        run: |
          # Create the key inside the actual dbt folder so profiles.yml can see it
          mkdir -p /ltv_sentinel_dbt/key
          echo "${{ secrets.GCP_SA_KEY }}" > LTV-Sentil/ltv_sentinel_dbt/key/service_account.json

      - name: Run dbt
        # We set the working directory so dbt starts exactly where dbt_project.yml lives
        working-directory: LTV-Sentil/ltv_sentinel_dbt
        env:
          DBT_GOOGLE_KEYFILE: key/service_account.json
        run: |
          dbt run --profiles-dir .
          dbt test --profiles-dir .