name: master_ltv_pipeline

on:
  schedule:
    - cron: '0 8 * * *'  # The whole thing runs at 8 AM
  workflow_dispatch:      # Manual trigger for testing

jobs:
  # JOB 1: Pull the data from the source
  ingest_data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Run Ingestion Script
        working-directory: ${{ github.workspace }}  
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          pip install pandas google-cloud-bigquery stripe
          python ${{ github.workspace }}/ingest_raw_script.py
         
  # JOB 2: Transform the data (only runs if ingest_data succeeds)
  run_dbt:
    needs: ingest_data  # <--- THIS IS THE MAGIC LINK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install dbt-bigquery

      - name: Create GCP service account key file
        run: |
          # Create the key folder in the root of the workspace
          mkdir -p ${{ github.workspace }}/key
          echo '${{ secrets.GCP_SA_KEY }}' > ${{ github.workspace }}/key/service_account.json

      - name: Create dbt profiles.yml
        run: |
          mkdir -p ~/.dbt
          cat <<EOF > ~/.dbt/profiles.yml
          ltv_sentinel_dbt:
            target: dev
            outputs:
              dev:
                type: bigquery
                method: service-account
                # Use the workspace variable here to guarantee the path is right
                keyfile: ${{ github.workspace }}/key/service_account.json
                project: ltv-sentinel-project
                dataset: ltv_sentinel_silver
                threads: 1
                timeout_seconds: 300
                location: US
                priority: interactive
          EOF

      - name: Debug dbt setup
        working-directory: ltv_sentinel_dbt
        run: dbt debug

      - name: Run dbt
        working-directory: ltv_sentinel_dbt
        run: |
          dbt run
          dbt test
